name: Build and Test Java with Gradle

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Make sure this version is supported by the setup-java action

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-8.1.1-bin.zip
        unzip -d /opt gradle-8.1.1-bin.zip
        export PATH=$PATH:/opt/gradle-8.1.1/bin

    - name: Build with Gradle
      run: gradle build --info  # Use --info for detailed output

    - name: Run tests
      run: gradle test

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs/*.jar  # Adjust the path to your built JARs or other artifacts
